name: Sync Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync_site_content:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare site contents
        run: |
          mkdir -p temp-site-content
          rsync -av --exclude='*.json' site/ temp-site-content/

      - name: Checkout 'generated' branch
        uses: actions/checkout@v4
        with:
          ref: generated
          path: generated
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy filtered site content into 'generated' branch directory
        run: |
          rsync -av --delete \
          --exclude='*.json' \
          --exclude='.git/*' \
          temp-site-content/ generated/

      - name: Check for changes and commit
        id: git-check
        run: |
          cd generated
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          if ! git diff --cached --exit-code; then
            RETRY_COUNT=0
            MAX_RETRIES=5
            SUCCESS=false

            while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
              COMMIT_MESSAGE="Chore: Synced site"

              git commit -m "$COMMIT_MESSAGE" || {
                echo "Commit failed, possibly no changes after rebase or concurrent commit. Retrying."
                git pull --rebase origin generated
                git add -A
              }

              if git push origin generated; then
                echo "Successfully pushed changes."
                SUCCESS=true
                break
              else
                echo "Push failed, retrying ($((RETRY_COUNT+1))/$MAX_RETRIES)..."
                git pull --rebase origin generated
                RETRY_COUNT=$((RETRY_COUNT+1))
              fi
              sleep 2
            done

            if [ "$SUCCESS" = "true" ]; then
              echo "::set-output name=committed::true"
            else
              echo "Failed to push changes after $MAX_RETRIES retries."
              exit 1 # Fail the step
            fi
          else
            echo "No changes to commit."
            echo "::set-output name=committed::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
