name: Update Loaders

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'site/*.json' 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Install Chrome dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgcc1 \
            libgdk-pixbuf2.0-0 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            libnss3-dev \
            lsb-release \
            xdg-utils \
            wget

      - name: Run the script
        run: bun getLoaders.js

      - name: Check for changes and commit
        id: git-check
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "site/loaders.json" -f
          if ! git diff --cached --exit-code; then
            RETRY_COUNT=0
            MAX_RETRIES=5
            SUCCESS=false

            while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
              COMMIT_MESSAGE="Chore: Updated loader versions"

              git commit -m "$COMMIT_MESSAGE" || {
                echo "Commit failed, possibly no changes after rebase or concurrent commit. Retrying."
                git pull --rebase
                git add "site/template.json" -f
              }

              if git push; then
                echo "Successfully pushed changes."
                SUCCESS=true
                break
              else
                echo "Push failed, retrying ($((RETRY_COUNT+1))/$MAX_RETRIES)..."
                git pull --rebase
                RETRY_COUNT=$((RETRY_COUNT+1))
              fi
              sleep 2
            done

            if [ "$SUCCESS" = "true" ]; then
              echo "::set-output name=committed::true"
            else
              echo "Failed to push changes after $MAX_RETRIES retries."
              exit 1
            fi
          else
            echo "No changes to commit."
            echo "::set-output name=committed::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}